#! /bin/sh

sxhkd &
fcitx &
#feh --bg-scale $HOME/Pictures/wallpapers/wallpaper.jpg
feh --bg-scale $HOME/dotfiles/Pictures/wallpapers/wallpaper.jpg
#$HOME/.config/polybar/launch.sh &
sh $HOME/.config/bspwm/autostart.sh&
xrdb $HOME/.Xresources&
xsetroot -cursor_name left_ptr&

#bspc monitor -d I II III IV V 
#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6 7 8 9
#bspc monitor -d HDMI-2 VI VII VIII IX X

#bspc config border_width         2
#bspc config window_gap          12
bspc config border_width         4
bspc config window_gap           1
#bspc config normal_border_color \#114422
bspc config focused_border_color \#119922

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a URxvt state=tiled follow=on
bspc rule -a Zathura state=tiled
bspc rule -a netease-cloud-music desktop='^9' state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#bspc rule -a Google-chrome desktop='^6' follow=on #state=floating 
bspc rule -a Chromium desktop='^6' follow=on #state=floating 
